### ISSUE TITLE
Enable multiplexing by default

### ISSUE THREAD

**Issue by wjziv** [RandomNinjaAtk/docker-locast2dvr#1]
Thanks for porting this through to Unraid! Basic functionality works as expected on Plex!

However, allowing `--override-zipcodes` may have the implication that the user could combine TV guides from different locations.

Would it make sense to allow multiplexing by default? If only one zipcode is declared, there is no effect. If there are more, then all channels are combined.

In the case of Plex, only the first of multiple tuners is 'visible' on the UI, even if they all have different channels.

**Comment by RandomNinjaAtk** [comment]
With the current setup, I'm successfully using multiple zipcodes. If you read the log, it'll show two different tuners on different ports. And you can add both to your Plex setup.

**Comment by wjziv** [comment]
I have. As I've mentioned:
> In the case of Plex, only the first of multiple tuners is 'visible' on the UI, even if they all have different channels.

Here is what I've set up on my server--each location is accessed on a separate port as an individual tuner.
![Screenshot 2021-03-17 10 07 30 AM](https://user-images.githubusercontent.com/29553646/111480963-e10ac680-8708-11eb-8ffa-9dd45c728233.png)

When I navigate to the server's Live TV tab, I find only the channels for the NY tuner.
![Screenshot 2021-03-17 10 11 29 AM](https://user-images.githubusercontent.com/29553646/111481339-3cd54f80-8709-11eb-9fa1-b46df876a307.png)

This changes if the NY tuner us removed.

Do you have your tuners connected differently?

**Comment by RandomNinjaAtk** [comment]
The change that was just pushed, is multiplex enabled. so update and give it a try

**Comment by wjziv** [comment]
This change worked just fine for me!
![image](https://user-images.githubusercontent.com/29553646/111484098-d0a81b00-870b-11eb-9bcd-c36e9cb2310c.png)

I'm still tugging at strings to find the XMLTV Guide, but I clearly have access to all expected channels, now. Thanks!

**Comment by RandomNinjaAtk** [comment]
the xml guide should be at http://X.X.X.X:6077/epg.xml
