### ISSUE TITLE
XML Guide inaccessible on Unraid

### ISSUE THREAD

**Issue by wjziv** [RandomNinjaAtk/docker-locast2dvr#2]
> the xml guide should be at http://X.X.X.X:6077/epg.xml

_Originally posted by @RandomNinjaAtk in https://github.com/RandomNinjaAtk/docker-locast2dvr/issues/1#issuecomment-801137824_

I don't necessarily see this to be the case on Unraid. Do you have a different experience? I'm wondering if there's something about port mapping in the Dockerfile.

**Comment by RandomNinjaAtk** [comment]
It works, its just slow to load... I think I need to further reduce the amount of days...

**Comment by wjziv** [comment]
So I messed around with the Unraid XML to contain the internal container network and make it what I considered 'proper' for Unraid. The result was fast XML access, whether it was 'slow to load' or failing to be accessed entirely. I'll continue this conversation on your Unraid template repo.
