### ISSUE TITLE
this is not a Issue but a ideal but i have no Clue were to post 

### ISSUE THREAD

**Issue by lawrence1986101** [RandomNinjaAtk/docker-locast2dvr#3]
I have been using your Docker locast2dvr works amazing Great Job! BTW also I was wondering if you could add in a feature to where in the Docker it has a patch to save the DVR Files I mean its, not a big deal but the docker works so well I don't see a reason not to have to were it's kinda like the Linux plex Docker with the GPU

**Comment by RandomNinjaAtk** [comment]
You should be able to use Emby/Jellyfin/Plex to record. I don't believe this software is designed to be a DVR. But those apps should be able to record the feed accordingly....

**Comment by lawrence1986101** [comment]
I mean don't get me wrong its perfect as is but that's really the only thing I can think of to make it even better than what is it already is but its really not a bad ideal since ton of new member are Jumping on unraid so they really don't know how to use Path, Port, Variable, 
    On Tuesday, March 30, 2021, 05:53:49 PM EDT, RandomNinjaAtk ***@***.***> wrote:  
 
 


You should be able to use Emby/Jellyfin/Plex to record. I don't believe this software is designed to be a DVR. But those apps should be able to record the feed accordingly....

**Comment by RandomNinjaAtk** [comment]
Not really sure what your asking with your last question, a template is already provided for most of the configurations.
