### ISSUE TITLE
docker-compose env quotations cause crash

### ISSUE THREAD

**Issue by cameronetchart** [RandomNinjaAtk/docker-locast2dvr#5]
The docker-compose instructions list:

```
- L2DUSER="username" \
- L2DPASS="password" \
- L2DZIP=#####,##### \
```

If you insert your env variables using quotations around the username and password as indicated, meaning:

```
"email@gmail.com"
"passwordhere"
```

then the container fails to start. The installation process inserts more quotations into the config file, creating a config that looks like:

```
username=""email@gmail.com""
password=""passwordhere""
```
This crashes the container with a config invalid error. If I omit the quotations from my env variables, then the generated config file adds one set of quotations and the container runs. But people often add quotations to env variables, especially for passwords with special characters. You could just remove the quotations from the readme.md, but guessing others will try to do what I did, so not sure the best way to solve since I don't program.

**Comment by RandomNinjaAtk** [comment]
Does it work with single quotes ?
```
- L2DUSER='username' \
```
```
username='email@gmail.com'
```

**Comment by cameronetchart** [comment]
No, it doesn't. It sends the single quotes to locast as part of the username, and locast rejects it.

**Comment by RandomNinjaAtk** [comment]
Well it should work without quotes. However, one thing I've found is depending on the characters in your password, it can break things... (special characters can be a problem at times...)

So give it a try with no quotes then... If you have some better way to handle it, I'm open to suggestions or PR's...
